# docker-compose.yml

version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: weather_postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d weather_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: weather_dashboard_app_container
    env_file:
      - .env
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    depends_on:
      postgres_db:
        condition: service_healthy
    # CMD will ONLY run the Dash app
    command: python src/dashboard/app.py

  pipeline: # NEW SERVICE FOR PIPELINE
    build: .
    container_name: weather_pipeline_container
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      postgres_db:
        condition: service_healthy
    # Command to run the pipeline script once
    command: python src/pipeline_orchestrator.py

volumes:
  pg_data: